name: npm-publish
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        
    # react项目为npm run-script build 
    - name: Install and Build
      run: |
        npm install
        npm run-script build
        cp build/index.html build/404.html

    # react项目的FOLDER为build 
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
